### ISSUE TITLE
about shape classification experiment

### ISSUE THREAD

**Issue by amiltonwong** [juho-lee/set_transformer#2]
Hi, @juho-lee ,

Thanks for releasing this package. Where could I find the code for modelnet 40 shape classification as mentioned in the paper?

THX!

**Comment by yoonholee** [comment]
Hi,

The code used for the paper was messy and also written in TensorFlow. I've pushed a reimplemented version and verified that the default hyperparameters roughly reproduce the results in the paper. You'll have to obtain the processed dataset (ModelNet40_cloud.h5) separately since we cannot publicly share it.

Thanks,
Yoonho Lee
